name: CI Pipeline


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI tests
        run: |
          python tests/test_api.py

      - name: Build Docker image
        run: docker build -t segment-app .

      - name: Lint code (Black + Flake8)
        run: |
          pip install black flake8
          black --check app/
          flake8 app/
