- name: Install dependencies
  run: pip install -r requirements.txt pytest

- name: Start FastAPI app
  run: uvicorn main:app --host 127.0.0.1 --port 8000 & sleep 5

- name: Run tests
  run: pytest test_api.py
